# Generated by Django 5.2.3 on 2025-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_data", models.JSONField(help_text="AI生成的完整报告数据")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, help_text="报告生成时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(help_text="用户订阅的领域关键词", max_length=255),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="分析频率，如 'weekly', 'monthly'", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, help_text="下一次报告生成的时间", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionFolder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="收藏夹名称")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否为默认收藏夹"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "收藏夹",
                "verbose_name_plural": "收藏夹",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500, verbose_name="文献标题")),
                (
                    "authors",
                    models.TextField(
                        help_text="作者列表，用逗号分隔", verbose_name="作者列表"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="期刊/会议"
                    ),
                ),
                (
                    "year",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="发表年份"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="摘要"),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="关键词列表，用逗号分隔",
                        null=True,
                        verbose_name="关键词",
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="本地文件路径",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="user_upload", max_length=50, verbose_name="文献来源"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="入库时间"
                    ),
                ),
                (
                    "research_fields",
                    models.TextField(blank=True, null=True, verbose_name="研究领域"),
                ),
                ("arxiv_url", models.URLField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "文献",
                "verbose_name_plural": "文献",
            },
        ),
        migrations.CreateModel(
            name="DocumentReadingHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "read_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="阅读时间"),
                ),
            ],
            options={
                "verbose_name": "文献阅读记录",
                "verbose_name_plural": "文献阅读记录",
                "ordering": ["-read_time"],
            },
        ),
        migrations.CreateModel(
            name="DocumentUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("self_uploaded", "自己上传"),
                            ("from_followed", "关注者上传"),
                            ("system_recommend", "系统推荐"),
                        ],
                        max_length=20,
                        verbose_name="文献来源类型",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "用户文献库条目",
                "verbose_name_plural": "用户文献库条目",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="FolderItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "收藏夹条目",
                "verbose_name_plural": "收藏夹条目",
            },
        ),
    ]
