# Generated by Django 5.2.3 on 2025-06-30 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="document.analysissubscription",
            ),
        ),
        migrations.AddField(
            model_name="collectionfolder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
        migrations.AddField(
            model_name="documentreadinghistory",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_by_users",
                to="document.document",
            ),
        ),
        migrations.AddField(
            model_name="documentreadinghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_reading_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentuser",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collected_by_users",
                to="document.document",
            ),
        ),
        migrations.AddField(
            model_name="documentuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folderitem",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_items",
                to="document.document",
                verbose_name="用户文献记录",
            ),
        ),
        migrations.AddField(
            model_name="folderitem",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="document.collectionfolder",
                verbose_name="所属收藏夹",
            ),
        ),
        migrations.AddField(
            model_name="folderitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏者",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analysissubscription",
            unique_together={("user", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="collectionfolder",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="documentuser",
            unique_together={("user", "document")},
        ),
        migrations.AlterUniqueTogether(
            name="folderitem",
            unique_together={("user", "folder", "document")},
        ),
    ]
