# Generated by Django 5.2.3 on 2025-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "conversation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="讨论主题"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("forum", "公开论坛"), ("project", "项目讨论组")],
                        default="forum",
                        max_length=10,
                        verbose_name="讨论类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "research_fields",
                    models.TextField(blank=True, null=True, verbose_name="研究领域"),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="简介"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
            ],
            options={
                "verbose_name": "讨论关注",
                "verbose_name_plural": "讨论关注",
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待批准"),
                            ("invited", "已邀请"),
                            ("approved", "已批准"),
                            ("admin", "管理员"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="参与状态",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
            ],
            options={
                "verbose_name": "讨论参与者",
                "verbose_name_plural": "讨论参与者",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "result_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="关联成果ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("group", "群组消息"),
                            ("user", "用户消息"),
                            ("invitation", "邀请消息"),
                            ("ask", "成果请求"),
                            ("system", "系统消息"),
                            ("claim", "认领成果"),
                            ("apply", "申请加入"),
                            ("forum", "论坛信息"),
                        ],
                        default="group",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
            ],
        ),
    ]
