# Generated by Django 5.2.3 on 2025-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("pub_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500, verbose_name="成果标题")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="成果类型"
                    ),
                ),
                (
                    "authors",
                    models.TextField(
                        help_text="作者列表，用逗号分隔", verbose_name="作者列表"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="期刊/会议"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="卷号"
                    ),
                ),
                (
                    "issue",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="期号"
                    ),
                ),
                (
                    "year",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="发表年份"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="摘要"),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="关键词列表，用逗号分隔",
                        null=True,
                        verbose_name="关键词",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="外部链接"
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="本地文件路径",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="上传时间"
                    ),
                ),
                (
                    "research_fields",
                    models.TextField(blank=True, null=True, verbose_name="研究领域"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationComment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="评论内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "成果关键词",
                "verbose_name_plural": "成果关键词",
            },
        ),
        migrations.CreateModel(
            name="PublicationLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "成果点赞",
                "verbose_name_plural": "成果点赞",
            },
        ),
        migrations.CreateModel(
            name="PublicationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "成果用户关联",
                "verbose_name_plural": "成果用户关联",
            },
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "read_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="阅读时间"),
                ),
            ],
            options={
                "verbose_name": "阅读记录",
                "verbose_name_plural": "阅读记录",
                "ordering": ["-read_time"],
            },
        ),
    ]
