# Generated by Django 5.2.3 on 2025-06-30 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_publications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
        migrations.AddField(
            model_name="publicationcomment",
            name="publication",
            field=models.ForeignKey(
                db_column="pub_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationkeyword",
            name="publication",
            field=models.ForeignKey(
                db_column="pub_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_keywords",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationlike",
            name="publication",
            field=models.ForeignKey(
                db_column="pub_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicationuser",
            name="publication",
            field=models.ForeignKey(
                db_column="pub_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="publicationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="readinghistory",
            name="publication",
            field=models.ForeignKey(
                db_column="pub_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_by_users",
                to="publications.publication",
            ),
        ),
        migrations.AddField(
            model_name="readinghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicationkeyword",
            unique_together={("publication", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="publicationlike",
            unique_together={("user", "publication")},
        ),
        migrations.AlterUniqueTogether(
            name="publicationuser",
            unique_together={("publication", "user")},
        ),
    ]
