import datetime
import json
import os
from typing import Dict, List, Optional
import arxiv
import asyncio

class ArxivScraper:
    def __init__(self, data_file: str = "arxiv_daily.json"):
        self.data_file = data_file
        self.client = arxiv.Client()
        self.ensure_data_file()

    def ensure_data_file(self):
        """确保数据文件存在"""
        if not os.path.exists(self.data_file):
            with open(self.data_file, "w") as f:
                json.dump({}, f)

    @staticmethod
    def format_authors(authors: List[any]) -> str:
        """格式化作者列表为逗号分隔的字符串"""
        return ", ".join(author.name for author in authors) if authors else ""
    
    @staticmethod
    def extract_year_from_date(date: datetime.date) -> Optional[int]:
        """从日期中提取年份"""
        return date.year if date else None

    async def fetch_papers(self, query: str, max_results: int = 10) -> List[Dict]:
        """
        获取论文数据
        :param query: 搜索查询
        :param max_results: 最大结果数量
        :return: 论文数据列表
        """
        papers = []
        
        search = arxiv.Search(
            query=query,
            max_results=max_results,
            sort_by=arxiv.SortCriterion.SubmittedDate,
            sort_order=arxiv.SortOrder.Descending
        )

        for result in self.client.results(search):
            paper_data = {
                'title': result.title,
                'authors': self.format_authors(result.authors),
                'journal': getattr(result, 'journal_ref', None) or "arXiv",
                'year': self.extract_year_from_date(result.published.date()),
                'abstract': result.summary,
                'keywords': getattr(result, 'primary_category', None),
                'source': 'arxiv',
                'research_fields': ", ".join(getattr(result, 'categories', [])),
                'arxiv_id': result.get_short_id(),
                'pdf_url': next((link.href for link in result.links if link.title == 'pdf'), None),
                'published_date': result.published.date().isoformat(),
                'updated_date': result.updated.date().isoformat() if hasattr(result, 'updated') else None,
                'comments': getattr(result, 'comment', "") or ""
            }
            papers.append(paper_data)
        
        return papers

    def update_data(self, new_data: Dict[str, List[Dict]]):
        """更新存储的论文数据"""
        try:
            with open(self.data_file, "r") as f:
                existing_data = json.load(f)
        except (json.JSONDecodeError, FileNotFoundError):
            existing_data = {}

        # 合并新数据
        for topic, papers in new_data.items():
            if topic in existing_data:
                existing_data[topic].extend(papers)
            else:
                existing_data[topic] = papers

        with open(self.data_file, "w") as f:
            json.dump(existing_data, f, indent=2)

    def generate_markdown(self, output_file: str = "README.md"):
        """生成Markdown格式的报告"""
        current_date = datetime.date.today().strftime("%Y.%m.%d")
        
        try:
            with open(self.data_file, "r") as f:
                data = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            data = {}

        with open(output_file, "w+") as f:
            f.write(f"## Updated on {current_date}\n\n")
            
            for topic, papers in data.items():
                if not papers:
                    continue
                    
                f.write(f"## {topic}\n\n")
                for paper in papers:
                    f.write(f"### {paper['title']}\n")
                    f.write(f"- **Authors**: {paper['authors']}\n")
                    f.write(f"- **Published**: {paper['published_date']}\n")
                    f.write(f"- **PDF**: [Link]({paper['pdf_url']})\n")
                    f.write(f"- **Abstract**: {paper['abstract'][:200]}...\n\n")

class ArxivDailyRunner:
    def __init__(self):
        self.scraper = ArxivScraper()
        self.topics = {
            # Artificial Intelligence (30 terms)
            "Artificial Intelligence": "AI OR 'artificial intelligence'",
            "Machine Learning": "machine learning OR ML",
            "Deep Learning": "deep learning OR neural networks",
            "Reinforcement Learning": "reinforcement learning OR RL",
            "Computer Vision": "computer vision OR CV",
            "Natural Language Processing": "NLP OR 'natural language processing'",
            "Expert Systems": "expert systems OR knowledge-based systems",
            "Fuzzy Logic": "fuzzy logic OR fuzzy systems",
            "Genetic Algorithms": "genetic algorithms OR evolutionary computation",
            "Swarm Intelligence": "swarm intelligence OR ant colony optimization",
            "Knowledge Representation": "knowledge representation OR ontologies",
            "Planning & Scheduling": "automated planning OR scheduling systems",
            "Decision Theory": "decision theory OR utility theory",
            "Cognitive Modeling": "cognitive modeling OR cognitive architectures",
            "Multi-Agent Systems": "multi-agent systems OR MAS",
            "AI Ethics": "AI ethics OR 'responsible AI'",
            "Explainable AI": "XAI OR 'explainable AI'",
            "AI Safety": "AI safety OR 'AI alignment'",
            "Transfer Learning": "transfer learning OR domain adaptation",
            "Few-Shot Learning": "few-shot learning OR one-shot learning",
            "Meta-Learning": "meta-learning OR 'learning to learn'",
            "Generative AI": "generative AI OR generative models",
            "AI Hardware": "AI accelerators OR neuromorphic computing",
            "Edge AI": "edge AI OR 'edge intelligence'",
            "AI Applications": "AI applications OR 'AI in industry'",
            "AI Governance": "AI governance OR 'AI policy'",
            "AI Benchmarking": "AI benchmarks OR MLPerf",
            "AI Security": "AI security OR 'adversarial ML'",
            "AI for Science": "AI for science OR 'scientific AI'",
            "General AI": "AGI OR 'general artificial intelligence'",

            # Computer Vision (50+)
            "Computer Vision": "computer vision OR CV",
            "Image Processing": "image processing OR digital image processing",
            "Object Detection": "object detection OR object recognition",
            "Image Segmentation": "image segmentation OR semantic segmentation OR instance segmentation",
            "Face Recognition": "face recognition OR facial recognition OR face detection",
            "Optical Character Recognition": "optical character recognition OR OCR",
            "Convolutional Neural Networks": "convolutional neural networks OR CNN",
            "YOLO": "YOLO OR you only look once",
            "ResNet": "ResNet OR residual networks",
            "Image Classification": "image classification OR visual classification",
            "Feature Extraction": "feature extraction OR SIFT OR SURF OR ORB",
            "Object Tracking": "object tracking OR visual tracking",
            "Pose Estimation": "pose estimation OR human pose estimation",
            "3D Reconstruction": "3D reconstruction OR structure from motion",
            "Augmented Reality": "augmented reality OR AR",
            "Medical Imaging": "medical imaging OR radiology imaging",
            "Autonomous Vehicles": "autonomous vehicles OR self-driving cars",
            "Generative Models": "generative adversarial networks OR GAN OR VAE",
            "Image Captioning": "image captioning OR visual captioning",
            "Video Analysis": "video analysis OR video understanding",
            "Depth Estimation": "depth estimation OR monocular depth estimation",
            "Neural Rendering": "neural rendering OR novel view synthesis",
            "Image Generation": "image generation OR text-to-image",
            "Visual Transformers": "visual transformers OR vision transformers",
            "Few-Shot Learning": "few-shot learning OR one-shot learning",

            # Machine Learning (60+)
            "Machine Learning": "machine learning OR ML",
            "Deep Learning": "deep learning OR neural networks",
            "Supervised Learning": "supervised learning",
            "Unsupervised Learning": "unsupervised learning",
            "Reinforcement Learning": "reinforcement learning OR RL",
            "Transfer Learning": "transfer learning OR domain adaptation",
            "Federated Learning": "federated learning OR decentralized learning",
            "Self-Supervised Learning": "self-supervised learning",
            "Semi-Supervised Learning": "semi-supervised learning",
            "Active Learning": "active learning",
            "Ensemble Learning": "ensemble learning OR random forest OR boosting",
            "Graph Neural Networks": "graph neural networks OR GNN",
            "Attention Mechanisms": "attention mechanisms OR transformer attention",
            "Explainable AI": "explainable AI OR XAI OR interpretable ML",
            "Bias in AI": "bias in AI OR algorithmic bias",
            "AI Ethics": "AI ethics OR ethical AI",
            "Hyperparameter Tuning": "hyperparameter tuning OR hyperparameter optimization",
            "Model Compression": "model compression OR pruning OR quantization",
            "AutoML": "AutoML OR automated machine learning",
            "Time Series Analysis": "time series analysis OR forecasting",
            "Anomaly Detection": "anomaly detection OR outlier detection",
            "Dimensionality Reduction": "dimensionality reduction OR PCA OR t-SNE",
            "Clustering": "clustering OR k-means OR DBSCAN",
            "Classification": "classification OR logistic regression OR SVM",
            "Regression": "regression OR linear regression",
            "Optimization": "optimization OR gradient descent",
            "Overfitting": "overfitting OR regularization",
            "Data Augmentation": "data augmentation",
            "Feature Engineering": "feature engineering",
            "MLOps": "MLOps OR machine learning operations",

            # Natural Language Processing (50+)
            "Natural Language Processing": "natural language processing OR NLP",
            "Text Classification": "text classification OR sentiment analysis",
            "Named Entity Recognition": "named entity recognition OR NER",
            "Machine Translation": "machine translation OR MT",
            "Question Answering": "question answering OR QA systems",
            "Text Generation": "text generation OR language generation",
            "Language Models": "language models OR BERT OR GPT",
            "Transformer Models": "transformer models OR attention models",
            "Word Embeddings": "word embeddings OR word2vec OR GloVe",
            "Text Summarization": "text summarization OR abstractive summarization",
            "Speech Recognition": "speech recognition OR ASR",
            "Speech Synthesis": "speech synthesis OR text-to-speech",
            "Information Extraction": "information extraction OR relation extraction",
            "Coreference Resolution": "coreference resolution",
            "Dependency Parsing": "dependency parsing",
            "Part-of-Speech Tagging": "part-of-speech tagging OR POS tagging",
            "Semantic Role Labeling": "semantic role labeling OR SRL",
            "Text Mining": "text mining OR text analytics",
            "Dialogue Systems": "dialogue systems OR chatbots",
            "Sentiment Analysis": "sentiment analysis OR opinion mining",
            "Topic Modeling": "topic modeling OR LDA",
            "Lexical Semantics": "lexical semantics OR word sense disambiguation",
            "Morphological Analysis": "morphological analysis",
            "Computational Linguistics": "computational linguistics",
            "Multilingual NLP": "multilingual NLP OR cross-lingual learning",

            # Web & Information Retrieval (50+)
            "Information Retrieval": "information retrieval OR IR",
            "Search Engines": "search engines OR web search",
            "Web Crawling": "web crawling OR web scraping",
            "Indexing": "indexing OR inverted index",
            "Ranking Algorithms": "ranking algorithms OR PageRank",
            "Recommender Systems": "recommender systems OR recommendation systems",
            "Content-Based Filtering": "content-based filtering",
            "Collaborative Filtering": "collaborative filtering",
            "Semantic Search": "semantic search OR vector search",
            "Query Understanding": "query understanding OR query expansion",
            "Document Retrieval": "document retrieval",
            "Text Similarity": "text similarity OR cosine similarity",
            "Knowledge Graphs": "knowledge graphs OR RDF",
            "Entity Linking": "entity linking OR named entity disambiguation",
            "Web Mining": "web mining OR web content mining",
            "Link Analysis": "link analysis OR hyperlink analysis",
            "Social Media Analysis": "social media analysis OR social network analysis",
            "Duplicate Detection": "duplicate detection OR near-duplicate detection",
            "Click-Through Rate": "click-through rate OR CTR prediction",
            "Personalization": "personalization OR personalized search",
            "Ad Targeting": "ad targeting OR computational advertising",
            "Question Retrieval": "question retrieval OR community question answering",
            "Vertical Search": "vertical search OR domain-specific search",
            "Federated Search": "federated search OR metasearch",
            "Query Log Analysis": "query log analysis",
            "Session Search": "session search OR multi-query search",

            # Computer Architecture (25 terms)
            "Computer Architecture": "computer architecture OR microarchitecture",
            "Processor Design": "processor design OR CPU design",
            "Instruction Set Architecture": "ISA OR 'instruction set architecture'",
            "RISC": "RISC OR 'reduced instruction set'",
            "CISC": "CISC OR 'complex instruction set'",
            "Pipelining": "pipelining OR pipeline hazards",
            "Superscalar": "superscalar OR out-of-order execution",
            "VLIW": "VLIW OR 'very long instruction word'",
            "Multicore": "multicore OR multi-core",
            "Cache": "cache OR cache hierarchy",
            "Memory Hierarchy": "memory hierarchy OR storage pyramid",
            "Virtual Memory": "virtual memory OR paging",
            "SIMD": "SIMD OR vector processing",
            "GPU": "GPU OR graphics processor",
            "TPU": "TPU OR tensor processor",
            "FPGA": "FPGA OR 'field programmable gate array'",
            "ASIC": "ASIC OR 'application specific IC'",
            "SoC": "SoC OR 'system on chip'",
            "Heterogeneous Computing": "heterogeneous computing",
            "Energy-Efficient Design": "energy-efficient OR low-power design",
            "3D IC": "3D IC OR 'three-dimensional integration'",
            "Approximate Computing": "approximate computing",
            "Quantum Computing": "quantum computing OR QPU",
            "Neuromorphic": "neuromorphic OR brain-inspired",
            "Secure Architecture": "secure architecture OR hardware security",

            # Computer Networks (25 terms)
            "Computer Networks": "computer networks OR networking",
            "TCP/IP": "TCP/IP OR internet protocol suite",
            "SDN": "SDN OR 'software defined networking'",
            "5G": "5G OR 'fifth generation'",
            "WiFi": "WiFi OR 802.11",
            "Ethernet": "Ethernet OR LAN",
            "Routing": "routing OR routing protocols",
            "BGP": "BGP OR 'border gateway protocol'",
            "QoS": "QoS OR 'quality of service'",
            "CDN": "CDN OR 'content delivery network'",
            "P2P": "P2P OR 'peer to peer'",
            "VPN": "VPN OR 'virtual private network'",
            "NFV": "NFV OR 'network function virtualization'",
            "IoT Networks": "IoT networks OR LPWAN",
            "Wireless Sensor": "wireless sensor OR WSN",
            "Network Security": "network security OR netsec",
            "Firewall": "firewall OR network firewall",
            "Intrusion Detection": "IDS OR 'intrusion detection'",
            "Traffic Analysis": "traffic analysis OR netflow",
            "Network Coding": "network coding OR coded packets",
            "Delay Tolerant": "delay tolerant OR DTN",
            "Satellite Networks": "satellite networks OR LEO",
            "Optical Networks": "optical networks OR fiber optics",
            "Network Virtualization": "network virtualization OR overlay",
            "Network Measurement": "network measurement OR probing",

            # Computer Security (25 terms)
            "Computer Security": "cybersecurity OR computer security",
            "Cryptography": "cryptography OR crypto",
            "Blockchain": "blockchain OR distributed ledger",
            "Malware": "malware OR virus OR worm",
            "Ransomware": "ransomware OR cryptoware",
            "Phishing": "phishing OR social engineering",
            "Zero-Day": "zero-day OR 0day",
            "Penetration Testing": "pen testing OR pentest",
            "Vulnerability": "vulnerability OR CVE",
            "Side-Channel": "side-channel OR timing attack",
            "Authentication": "authentication OR MFA",
            "Authorization": "authorization OR access control",
            "Privacy": "privacy OR GDPR",
            "Anonymity": "anonymity OR Tor",
            "Forensics": "forensics OR digital forensics",
            "Honeypot": "honeypot OR deception",
            "Sandboxing": "sandboxing OR isolation",
            "Reverse Engineering": "reverse engineering OR RE",
            "Secure Coding": "secure coding OR DevSecOps",
            "Threat Modeling": "threat modeling OR STRIDE",
            "Security Protocols": "security protocols OR TLS",
            "Biometric Security": "biometric OR fingerprint",
            "Post-Quantum": "post-quantum OR quantum-safe",
            "Security Analytics": "security analytics OR SIEM",
            "Incident Response": "incident response OR IR",

            # Databases (20 terms)
            "Databases": "databases OR DBMS",
            "SQL": "SQL OR 'structured query'",
            "NoSQL": "NoSQL OR 'non-relational'",
            "NewSQL": "NewSQL OR scalable SQL",
            "Relational": "relational OR RDBMS",
            "Document": "document OR MongoDB",
            "Key-Value": "key-value OR Redis",
            "Columnar": "columnar OR column-store",
            "Graph": "graph OR Neo4j",
            "Time Series": "time series OR TSDB",
            "In-Memory": "in-memory OR IMDB",
            "Distributed": "distributed OR sharding",
            "Transaction": "transaction OR ACID",
            "Consistency": "consistency OR CAP",
            "Indexing": "indexing OR B-tree",
            "Query Optimization": "query optimization OR plan",
            "Data Warehouse": "data warehouse OR OLAP",
            "ETL": "ETL OR 'extract transform'",
            "Database Security": "database security OR SQLi",
            "Blockchain Database": "blockchain database OR ledger DB",

            # Design Automation (15 terms)
            "Design Automation": "EDA OR 'electronic design'",
            "HDL": "HDL OR 'hardware description'",
            "Verilog": "Verilog OR SystemVerilog",
            "VHDL": "VHDL OR VHSIC",
            "Logic Synthesis": "logic synthesis OR RTL",
            "Place & Route": "place and route OR PnR",
            "FPGA Tools": "FPGA tools OR HLS",
            "ASIC Design": "ASIC design OR tapeout",
            "Formal Verification": "formal verification OR model checking",
            "Physical Design": "physical design OR layout",
            "DFT": "DFT OR 'design for test'",
            "Power Analysis": "power analysis OR IR drop",
            "Timing Analysis": "timing analysis OR STA",
            "Analog Design": "analog design OR mixed-signal",
            "IP Cores": "IP cores OR semiconductor IP",

            # Embedded & Real-Time Systems (20 terms)
            "Embedded Systems": "embedded OR 'embedded systems'",
            "Real-Time": "real-time OR RTOS",
            "Microcontroller": "microcontroller OR MCU",
            "RTOS": "RTOS OR 'real-time OS'",
            "Firmware": "firmware OR device driver",
            "IoT Devices": "IoT devices OR smart devices",
            "Edge Devices": "edge devices OR gateway",
            "Sensor Networks": "sensor networks OR mote",
            "Wearables": "wearables OR wearable tech",
            "Automotive": "automotive OR ECU",
            "Avionics": "avionics OR DO-178",
            "Industrial Control": "industrial OR PLC",
            "Medical Devices": "medical devices OR FDA",
            "Energy Harvesting": "energy harvesting OR EH",
            "Safety-Critical": "safety-critical OR SIL",
            "Reliability": "reliability OR fault tolerance",
            "Low Power": "low power OR energy efficient",
            "Memory Constraints": "memory constraints OR tinyML",
            "Real-Time Scheduling": "real-time scheduling OR EDF",
            "Hardware/Software": "hardware/software OR HW/SW",

            # High-Performance Computing (15 terms)
            "HPC": "HPC OR 'high performance'",
            "Supercomputing": "supercomputing OR TOP500",
            "Parallel Computing": "parallel OR MPI",
            "Distributed Computing": "distributed OR grid",
            "Cluster": "cluster OR Beowulf",
            "Cloud HPC": "cloud HPC OR HPCaaS",
            "GPU Computing": "GPU computing OR CUDA",
            "Exascale": "exascale OR zettascale",
            "Scientific Computing": "scientific OR numerical",
            "Big Data": "big data OR Hadoop",
            "MapReduce": "MapReduce OR Spark",
            "Performance Modeling": "performance modeling OR roofline",
            "Vectorization": "vectorization OR SIMD",
            "Load Balancing": "load balancing OR work stealing",
            "Fault Tolerance": "fault tolerance OR checkpointing",

            # Mobile Computing (15 terms)
            "Mobile Computing": "mobile OR smartphones",
            "Android": "Android OR AOSP",
            "iOS": "iOS OR Apple mobile",
            "Mobile Apps": "mobile apps OR app development",
            "Location Services": "GPS OR location services",
            "Mobile Sensors": "mobile sensors OR accelerometer",
            "Mobile Networks": "mobile networks OR cellular",
            "5G Mobile": "5G mobile OR mmWave",
            "Mobile Security": "mobile security OR app security",
            "Mobile Payments": "mobile payments OR wallets",
            "AR Mobile": "AR mobile OR mobile AR",
            "Wearable Tech": "wearable tech OR smartwatch",
            "Mobile Cloud": "mobile cloud OR MCC",
            "Edge Computing": "edge computing OR MEC",
            "Mobile Web": "mobile web OR PWA",

            # Measurement & Performance Analysis (15 terms)
            "Performance Analysis": "performance OR benchmarking",
            "Profiling": "profiling OR performance counters",
            "Tracing": "tracing OR dtrace",
            "Monitoring": "monitoring OR observability",
            "Metrics": "metrics OR telemetry",
            "Workload": "workload OR characterization",
            "Microbenchmark": "microbenchmark OR nanobench",
            "Latency": "latency OR response time",
            "Throughput": "throughput OR bandwidth",
            "Scalability": "scalability OR scale-out",
            "Bottleneck": "bottleneck OR hot spot",
            "Resource Usage": "resource usage OR utilization",
            "Power Measurement": "power OR energy measurement",
            "Performance Debugging": "performance debugging OR tuning",
            "Statistical Analysis": "statistical OR significance",

            # Operating Systems (20 terms)
            "Operating Systems": "OS OR 'operating system'",
            "Kernel": "kernel OR microkernel",
            "Linux": "Linux OR GNU/Linux",
            "Windows": "Windows OR Win32",
            "macOS": "macOS OR Darwin",
            "Unix": "Unix OR POSIX",
            "Virtualization": "virtualization OR hypervisor",
            "Containers": "containers OR Docker",
            "File Systems": "file systems OR filesystem",
            "Memory Management": "memory OR paging",
            "Process Scheduling": "scheduling OR scheduler",
            "Device Drivers": "drivers OR device driver",
            "System Calls": "syscalls OR system calls",
            "Security": "OS security OR SELinux",
            "Real-Time OS": "RTOS OR 'real-time OS'",
            "Embedded OS": "embedded OS OR QNX",
            "Distributed OS": "distributed OS OR Plan9",
            "Unikernel": "unikernel OR library OS",
            "Firmware": "firmware OR UEFI",
            "Boot Process": "boot OR BIOS",

            # Programming Languages (20 terms)
            "Programming Languages": "PL OR 'programming language'",
            "Compilers": "compilers OR compiler design",
            "Interpreters": "interpreters OR JIT",
            "Type Systems": "type systems OR static typing",
            "Functional": "functional OR lambda calculus",
            "Object-Oriented": "OOP OR 'object oriented'",
            "Concurrent": "concurrent OR parallelism",
            "Scripting": "scripting OR dynamic languages",
            "Memory Safety": "memory safety OR borrow checker",
            "Garbage Collection": "GC OR 'garbage collection'",
            "Syntax": "syntax OR grammar",
            "Semantics": "semantics OR formal methods",
            "Domain-Specific": "DSL OR 'domain specific'",
            "Low-Level": "low-level OR assembly",
            "High-Level": "high-level OR abstraction",
            "Type Theory": "type theory OR category",
            "Language Design": "language design OR PLDI",
            "Runtime Systems": "runtime OR VM",
            "Debugging": "debugging OR symbolic execution",
            "Language Security": "language security OR sandboxing",

            # Software Engineering (25 terms)
            "Software Engineering": "SE OR 'software engineering'",
            "Agile": "agile OR scrum",
            "DevOps": "DevOps OR CI/CD",
            "Testing": "testing OR unit tests",
            "QA": "QA OR 'quality assurance'",
            "Requirements": "requirements OR SRS",
            "Design Patterns": "design patterns OR GoF",
            "UML": "UML OR modeling",
            "Refactoring": "refactoring OR code smells",
            "Code Review": "code review OR peer review",
            "Static Analysis": "static analysis OR linters",
            "Dynamic Analysis": "dynamic analysis OR fuzzing",
            "Formal Methods": "formal methods OR TLA+",
            "Software Architecture": "architecture OR microservices",
            "API Design": "API OR 'application programming'",
            "Documentation": "documentation OR README",
            "Version Control": "git OR version control",
            "Open Source": "open source OR FOSS",
            "Maintenance": "maintenance OR legacy",
            "Technical Debt": "technical debt OR code debt",
            "Metrics": "metrics OR code metrics",
            "Security Engineering": "security OR DevSecOps",
            "Dependability": "dependability OR fault tolerance",
            "Empirical SE": "empirical OR case studies",
            "Human Factors": "human factors OR usability",

            # Algorithms & Complexity (80 terms)
            "Algorithms": "algorithms OR algorithmic",
            "Complexity Theory": "complexity theory OR computational complexity",
            "Time Complexity": "time complexity OR running time",
            "Space Complexity": "space complexity OR memory usage",
            "Big O Notation": "Big O OR asymptotic notation",
            "P vs NP": "P vs NP OR P=NP",
            "NP-Completeness": "NP-complete OR NP-hard",
            "Approximation Algorithms": "approximation algorithms OR approximation schemes",
            "Randomized Algorithms": "randomized algorithms OR probabilistic algorithms",
            "Parallel Algorithms": "parallel algorithms OR concurrent algorithms",
            "Distributed Algorithms": "distributed algorithms OR consensus algorithms",
            "Online Algorithms": "online algorithms OR competitive analysis",
            "Streaming Algorithms": "streaming algorithms OR sublinear algorithms",
            "Graph Algorithms": "graph algorithms OR network algorithms",
            "Shortest Path": "shortest path OR Dijkstra",
            "Minimum Spanning Tree": "minimum spanning tree OR MST",
            "Maximum Flow": "maximum flow OR min-cut",
            "Matching Algorithms": "matching algorithms OR bipartite matching",
            "Graph Coloring": "graph coloring OR chromatic number",
            "Clique Problem": "clique problem OR maximal clique",
            "Traveling Salesman": "TSP OR traveling salesman",
            "Sorting Algorithms": "sorting OR quicksort OR mergesort",
            "Search Algorithms": "search algorithms OR binary search",
            "Dynamic Programming": "dynamic programming OR memoization",
            "Greedy Algorithms": "greedy algorithms OR local optimization",
            "Divide and Conquer": "divide and conquer OR recursive algorithms",
            "Backtracking": "backtracking OR branch and bound",
            "Branch and Bound": "branch and bound OR B&B",
            "Linear Programming": "linear programming OR LP",
            "Integer Programming": "integer programming OR ILP",
            "Constraint Programming": "constraint programming OR CSP",
            "Combinatorial Optimization": "combinatorial optimization OR discrete optimization",
            "Geometric Algorithms": "geometric algorithms OR computational geometry",
            "Convex Hull": "convex hull OR Jarvis march",
            "Voronoi Diagrams": "Voronoi diagrams OR Delaunay triangulation",
            "Numerical Algorithms": "numerical algorithms OR numerical analysis",
            "Matrix Algorithms": "matrix algorithms OR matrix multiplication",
            "FFT": "FFT OR fast Fourier transform",
            "Number Theory Algorithms": "number theory algorithms OR primality testing",
            "String Algorithms": "string algorithms OR text processing",
            "Pattern Matching": "pattern matching OR string matching",
            "Edit Distance": "edit distance OR Levenshtein",
            "Compression Algorithms": "compression algorithms OR data compression",
            "Cryptographic Algorithms": "cryptographic algorithms OR crypto primitives",
            "Quantum Algorithms": "quantum algorithms OR Shor's algorithm",
            "Machine Learning Algorithms": "machine learning algorithms OR ML models",
            "Data Structures": "data structures OR abstract data types",
            "Arrays": "arrays OR vectors",
            "Linked Lists": "linked lists OR pointers",
            "Stacks": "stacks OR LIFO",
            "Queues": "queues OR FIFO",
            "Hash Tables": "hash tables OR dictionaries",
            "Trees": "trees OR binary trees",
            "Binary Search Trees": "binary search trees OR BST",
            "AVL Trees": "AVL trees OR balanced trees",
            "Red-Black Trees": "red-black trees OR RB trees",
            "B-Trees": "B-trees OR B+ trees",
            "Heaps": "heaps OR priority queues",
            "Graph Representations": "graph representations OR adjacency lists",
            "Trie": "trie OR prefix tree",
            "Bloom Filters": "Bloom filters OR probabilistic data structures",
            "Skip Lists": "skip lists OR probabilistic structures",
            "Disjoint Sets": "disjoint sets OR union-find",
            "Amortized Analysis": "amortized analysis OR aggregate method",
            "Lower Bounds": "lower bounds OR information theory",
            "Circuit Complexity": "circuit complexity OR Boolean circuits",
            "Communication Complexity": "communication complexity OR Yao's principle",
            "Parameterized Complexity": "parameterized complexity OR fixed-parameter",
            "Approximation Hardness": "approximation hardness OR inapproximability",
            "Randomness in Computation": "randomness OR pseudorandomness",
            "Derandomization": "derandomization OR PRGs",
            "Computational Geometry": "computational geometry OR geometric computing",
            "Online Learning": "online learning OR expert algorithms",
            "Algorithmic Game Theory": "algorithmic game theory OR mechanism design",
            "Fair Division": "fair division OR cake cutting",
            "Scheduling Algorithms": "scheduling algorithms OR job scheduling",
            "Routing Algorithms": "routing algorithms OR path finding",
            "Evolutionary Algorithms": "evolutionary algorithms OR genetic programming",

            # Cryptography (70 terms)
            "Cryptography": "cryptography OR crypto",
            "Symmetric Cryptography": "symmetric OR secret-key",
            "AES": "AES OR 'advanced encryption'",
            "DES": "DES OR 'data encryption'",
            "Block Ciphers": "block ciphers OR Feistel",
            "Stream Ciphers": "stream ciphers OR RC4",
            "Public-Key Cryptography": "public-key OR asymmetric",
            "RSA": "RSA OR Rivest-Shamir-Adleman",
            "Elliptic Curve": "ECC OR 'elliptic curve'",
            "Diffie-Hellman": "Diffie-Hellman OR key exchange",
            "Digital Signatures": "digital signatures OR DSA",
            "Hash Functions": "hash functions OR cryptographic hashing",
            "SHA": "SHA OR 'secure hash'",
            "MAC": "MAC OR 'message authentication'",
            "HMAC": "HMAC OR keyed-hash",
            "PKI": "PKI OR 'public key infrastructure'",
            "Certificates": "certificates OR X.509",
            "TLS": "TLS OR SSL",
            "SSL": "SSL OR 'secure sockets'",
            "VPN Protocols": "VPN OR IPsec",
            "Zero-Knowledge": "zero-knowledge OR ZKP",
            "Homomorphic Encryption": "homomorphic OR FHE",
            "Multi-Party Computation": "MPC OR 'secure computation'",
            "Oblivious Transfer": "oblivious transfer OR OT",
            "Commitment Schemes": "commitment OR cryptographic commitment",
            "Threshold Cryptography": "threshold OR secret sharing",
            "Post-Quantum Crypto": "post-quantum OR quantum-resistant",
            "Lattice-Based": "lattice-based OR NTRU",
            "Code-Based": "code-based OR McEliece",
            "Hash-Based": "hash-based OR Merkle",
            "Multivariate": "multivariate OR oil-vinegar",
            "Side-Channel Attacks": "side-channel OR timing attacks",
            "Differential Cryptanalysis": "differential OR Biham-Shamir",
            "Linear Cryptanalysis": "linear OR Matsui",
            "Algebraic Attacks": "algebraic OR SAT solvers",
            "Related-Key Attacks": "related-key OR key schedule",
            "Birthday Attack": "birthday OR collision attack",
            "Man-in-the-Middle": "MITM OR 'man in the middle'",
            "Replay Attacks": "replay OR nonce reuse",
            "Padding Oracle": "padding oracle OR Bleichenbacher",
            "Cryptographic Protocols": "protocols OR cryptographic schemes",
            "OAuth": "OAuth OR OpenID",
            "Kerberos": "Kerberos OR authentication protocol",
            "Secure Messaging": "secure messaging OR Signal",
            "Blockchain Crypto": "blockchain OR consensus algorithms",
            "Mining Algorithms": "mining OR proof-of-work",
            "Smart Contracts": "smart contracts OR Ethereum",
            "Privacy Coins": "privacy coins OR Zcash",
            "Mix Networks": "mix networks OR onion routing",
            "Secure Voting": "secure voting OR e-voting",
            "Anonymous Credentials": "anonymous OR pseudonymous",
            "Fuzzy Extractors": "fuzzy OR biometric crypto",
            "Quantum Cryptography": "quantum OR QKD",
            "Post-Quantum Standards": "NIST PQC OR standardization",
            "Cryptanalysis": "cryptanalysis OR breaking crypto",
            "Implementation Security": "implementation OR constant-time",
            "White-Box Crypto": "white-box OR obfuscation",
            "Provable Security": "provable OR reduction proofs",
            "Random Oracles": "random oracle model OR ROM",
            "Standard Model": "standard model OR concrete security",
            "Information-Theoretic": "information-theoretic OR perfect secrecy",
            "Game-Based": "game-based OR simulation",
            "Universal Composability": "UC OR composability",
            "Secure Hardware": "HSM OR 'hardware security'",
            "Trusted Execution": "TEE OR SGX",
            "Secure Enclaves": "enclaves OR trusted computing",
            "Cryptocurrencies": "cryptocurrencies OR digital cash",
            "Privacy Protocols": "privacy OR anonymity",

            # Logic & Verification (60 terms)
            "Mathematical Logic": "mathematical logic OR formal logic",
            "Propositional Logic": "propositional OR Boolean logic",
            "First-Order Logic": "FOL OR 'first order'",
            "Higher-Order Logic": "HOL OR 'higher order'",
            "Modal Logic": "modal OR temporal logic",
            "Temporal Logic": "temporal OR LTL",
            "Description Logic": "description OR DL",
            "Fuzzy Logic": "fuzzy OR many-valued",
            "Intuitionistic Logic": "intuitionistic OR constructive",
            "Linear Logic": "linear OR resource logic",
            "Proof Theory": "proof theory OR natural deduction",
            "Model Theory": "model theory OR satisfiability",
            "Recursion Theory": "recursion OR computability",
            "Type Theory": "type theory OR typed lambda",
            "Hoare Logic": "Hoare OR axiomatic semantics",
            "Separation Logic": "separation OR pointer logic",
            "Dynamic Logic": "dynamic OR program logic",
            "Process Calculi": "process OR pi-calculus",
            "Automata Theory": "automata OR finite state",
            "Turing Machines": "Turing OR computability",
            "Lambda Calculus": "lambda OR functional calculus",
            "Combinatory Logic": "combinatory OR SKI",
            "Category Theory": "category OR monads",
            "Formal Verification": "formal verification OR model checking",
            "Model Checking": "model checking OR temporal logic",
            "Theorem Proving": "theorem proving OR proof assistants",
            "SAT Solving": "SAT OR satisfiability",
            "SMT": "SMT OR 'satisfiability modulo'",
            "Static Analysis": "static analysis OR abstract interpretation",
            "Abstract Interpretation": "abstract interpretation OR Galois connections",
            "Program Analysis": "program analysis OR verification",
            "Symbolic Execution": "symbolic execution OR concolic",
            "Bounded Model Checking": "bounded OR BMC",
            "Termination Analysis": "termination OR halting problem",
            "Program Synthesis": "program synthesis OR inductive",
            "Formal Methods": "formal methods OR rigorous methods",
            "Specification Languages": "specification OR TLA+",
            "Alloy": "Alloy OR lightweight formal",
            "Z Notation": "Z OR formal specification",
            "VDM": "VDM OR 'Vienna development'",
            "Coq": "Coq OR proof assistant",
            "Isabelle": "Isabelle OR HOL",
            "Agda": "Agda OR dependent types",
            "Lean": "Lean OR theorem prover",
            "PVS": "PVS OR 'prototype verification'",
            "ACL2": "ACL2 OR computational logic",
            "SPIN": "SPIN OR model checker",
            "NuSMV": "NuSMV OR symbolic model",
            "UPPAAL": "UPPAAL OR timed automata",
            "PRISM": "PRISM OR probabilistic model",
            "CBMC": "CBMC OR 'C bounded model'",
            "K Framework": "K OR semantic framework",
            "Runtime Verification": "runtime OR monitoring",
            "Contract-Based": "contracts OR design by contract",
            "Refinement": "refinement OR stepwise",
            "Correctness Proofs": "correctness OR verification proofs",
            "Program Logic": "program logic OR Floyd-Hoare",
            "Concurrency Verification": "concurrency OR process algebra",
            "Hardware Verification": "hardware OR circuit verification",
            "Protocol Verification": "protocol OR security verification",

            # Computational Biology & Bioinformatics (40 terms)
            "Computational Biology": "computational biology OR bioinformatics",
            "Genomics": "genomics OR genome analysis",
            "DNA Sequencing": "DNA sequencing OR NGS",
            "RNA-Seq": "RNA-seq OR transcriptomics",
            "Proteomics": "proteomics OR protein analysis",
            "Metabolomics": "metabolomics OR metabolic networks",
            "Phylogenetics": "phylogenetics OR evolutionary trees",
            "Sequence Alignment": "sequence alignment OR BLAST",
            "Multiple Alignment": "multiple alignment OR MSA",
            "Gene Prediction": "gene prediction OR ORF finding",
            "Variant Calling": "variant calling OR SNP detection",
            "Structural Bioinformatics": "structural bioinformatics OR protein structure",
            "Molecular Docking": "molecular docking OR drug design",
            "Protein Folding": "protein folding OR folding prediction",
            "Systems Biology": "systems biology OR biological networks",
            "Pathway Analysis": "pathway analysis OR metabolic pathways",
            "Single-Cell Analysis": "single-cell OR scRNA-seq",
            "Microbiome": "microbiome OR metagenomics",
            "CRISPR": "CRISPR OR gene editing",
            "Drug Discovery": "drug discovery OR virtual screening",
            "Neuroscience": "computational neuroscience OR brain modeling",
            "Population Genetics": "population genetics OR GWAS",
            "Epigenetics": "epigenetics OR DNA methylation",
            "Cancer Genomics": "cancer genomics OR oncogenomics",
            "Immunoinformatics": "immunoinformatics OR vaccine design",
            "Biological Networks": "biological networks OR PPI",
            "Gene Regulation": "gene regulation OR TF binding",
            "Comparative Genomics": "comparative genomics OR synteny",
            "Assembly Algorithms": "assembly OR genome assembly",
            "Metagenomics": "metagenomics OR environmental sequencing",
            "Biological Databases": "biological databases OR NCBI",
            "Machine Learning in Bio": "ML in biology OR bio ML",
            "AI for Drug Discovery": "AI drug discovery OR deep learning",
            "Clinical Bioinformatics": "clinical bioinformatics OR precision medicine",
            "Evolutionary Biology": "evolutionary biology OR phylogenomics",
            "Synthetic Biology": "synthetic biology OR genetic circuits",
            "Biomedical Imaging": "biomedical imaging OR medical image analysis",
            "Cheminformatics": "cheminformatics OR molecular descriptors",
            "Biological Modeling": "biological modeling OR ODE models",
            "Bioinformatics Tools": "bioinformatics tools OR Bioconductor",

            # Computer Graphics (40 terms)
            "Computer Graphics": "computer graphics OR CG",
            "Rendering": "rendering OR ray tracing",
            "Real-Time Rendering": "real-time rendering OR game graphics",
            "Global Illumination": "global illumination OR photon mapping",
            "Shading": "shading OR BRDF",
            "Texturing": "texturing OR texture mapping",
            "Procedural Generation": "procedural generation OR noise algorithms",
            "Geometry Processing": "geometry processing OR mesh editing",
            "3D Modeling": "3D modeling OR digital sculpting",
            "Animation": "animation OR character rigging",
            "Physically-Based": "PBR OR physically-based rendering",
            "GPU Programming": "GPU programming OR shaders",
            "OpenGL": "OpenGL OR Vulkan",
            "DirectX": "DirectX OR graphics API",
            "Virtual Reality": "VR OR virtual reality",
            "Augmented Reality": "AR OR augmented reality",
            "Mixed Reality": "MR OR mixed reality",
            "Image Synthesis": "image synthesis OR rendering equation",
            "Non-Photorealistic": "NPR OR non-photorealistic",
            "Computational Photography": "computational photography OR HDR",
            "Light Transport": "light transport OR path tracing",
            "Subsurface Scattering": "subsurface scattering OR SSS",
            "Volume Rendering": "volume rendering OR medical visualization",
            "Point-Based Graphics": "point-based graphics OR splatting",
            "Facial Animation": "facial animation OR blendshapes",
            "Motion Capture": "motion capture OR mocap",
            "Fluid Simulation": "fluid simulation OR smoke effects",
            "Cloth Simulation": "cloth simulation OR fabric modeling",
            "Hair Rendering": "hair rendering OR fur simulation",
            "Particle Systems": "particle systems OR effects",
            "Procedural Animation": "procedural animation OR physics-based",
            "Image-Based Rendering": "image-based OR IBR",
            "Matting": "matting OR alpha compositing",
            "Morphing": "morphing OR shape interpolation",
            "Level of Detail": "LOD OR level of detail",
            "Collision Detection": "collision detection OR physics engines",
            "Radiosity": "radiosity OR finite element",
            "Caustics": "caustics OR photon effects",
            "Real-Time Shadows": "shadows OR shadow mapping",
            "GPU Acceleration": "GPU acceleration OR CUDA rendering",

            # Computer Science Education (30 terms)
            "CS Education": "CS education OR computer science education",
            "Computational Thinking": "computational thinking OR problem solving",
            "Programming Pedagogy": "programming pedagogy OR teaching coding",
            "Active Learning": "active learning OR engagement techniques",
            "Peer Instruction": "peer instruction OR classroom voting",
            "Block-Based Programming": "block-based OR Scratch",
            "Text-Based Programming": "text-based OR Python teaching",
            "CS Unplugged": "CS unplugged OR offline activities",
            "Curriculum Design": "curriculum design OR CS standards",
            "Assessment": "assessment OR programming evaluation",
            "Debugging Skills": "debugging OR error diagnosis",
            "Novice Programmers": "novices OR beginner programmers",
            "Misconceptions": "misconceptions OR programming myths",
            "CS1": "CS1 OR introductory programming",
            "Data Structures Education": "data structures teaching OR DS pedagogy",
            "Algorithm Education": "algorithm education OR algo teaching",
            "K-12 CS": "K-12 OR primary education",
            "AP CS": "AP CS OR advanced placement",
            "Diversity in CS": "diversity OR inclusion in CS",
            "Gender Gap": "gender gap OR women in CS",
            "Equity": "equity OR access to CS",
            "Online Learning": "online learning OR MOOCs",
            "Educational Tools": "educational tools OR programming IDEs",
            "Visualization Tools": "visualization OR program animation",
            "CS Teacher Training": "teacher training OR PD",
            "Ethics Education": "ethics OR responsible computing",
            "AI Education": "AI education OR ML teaching",
            "Robotics Education": "educational robotics OR robot kits",
            "Physical Computing": "physical computing OR Arduino",
            "Outreach Programs": "outreach OR after-school programs",

            # Economics & Computation (30 terms)
            "Algorithmic Game Theory": "algorithmic game theory OR AGT",
            "Mechanism Design": "mechanism design OR auction theory",
            "Auction Algorithms": "auctions OR bidding strategies",
            "Matching Markets": "matching OR stable marriage",
            "Price of Anarchy": "price of anarchy OR inefficiency",
            "Social Choice": "social choice OR voting theory",
            "Fair Division": "fair division OR cake cutting",
            "Computational Social Choice": "computational social choice OR COMSOC",
            "Network Economics": "network economics OR graph models",
            "Information Markets": "information markets OR prediction markets",
            "Blockchain Economics": "blockchain OR crypto economics",
            "Incentive Compatibility": "incentives OR strategy-proof",
            "Reputation Systems": "reputation OR trust systems",
            "Two-Sided Markets": "two-sided OR platform markets",
            "Sponsored Search": "sponsored search OR ad auctions",
            "Combinatorial Auctions": "combinatorial OR package bidding",
            "Procurement": "procurement OR reverse auctions",
            "Peer Prediction": "peer prediction OR information elicitation",
            "Contract Theory": "contract theory OR principal-agent",
            "Labor Markets": "labor OR job matching",
            "School Choice": "school choice OR student assignment",
            "Kidney Exchange": "kidney exchange OR organ allocation",
            "Privacy Economics": "privacy OR data valuation",
            "Algorithmic Pricing": "algorithmic pricing OR dynamic pricing",
            "Attention Economies": "attention OR information overload",
            "Behavioral Game Theory": "behavioral OR bounded rationality",
            "Learning in Games": "learning OR evolutionary game theory",
            "Equilibrium Computation": "equilibrium OR Nash computation",
            "Market Design": "market design OR institutional design",
            "Computational Finance": "computational finance OR algorithmic trading",

            # Human-Computer Interaction (40 terms)
            "HCI": "HCI OR human-computer interaction",
            "User Interfaces": "user interfaces OR UI design",
            "User Experience": "UX OR user experience",
            "Usability": "usability OR user testing",
            "Accessibility": "accessibility OR inclusive design",
            "Interaction Design": "interaction design OR IxD",
            "Information Visualization": "information visualization OR infovis",
            "Visual Analytics": "visual analytics OR VA",
            "User Studies": "user studies OR empirical methods",
            "Participatory Design": "participatory OR co-design",
            "Context-Aware": "context-aware OR situational computing",
            "Ubiquitous Computing": "ubiquitous OR pervasive computing",
            "Wearable Computing": "wearables OR smart devices",
            "Tangible Interfaces": "tangible OR physical interfaces",
            "Gesture Recognition": "gestures OR motion sensing",
            "Voice Interfaces": "voice OR conversational interfaces",
            "Eye Tracking": "eye tracking OR gaze interaction",
            "Haptics": "haptics OR tactile feedback",
            "Brain-Computer": "BCI OR brain-computer",
            "AR Interfaces": "AR interfaces OR mixed reality",
            "VR Interfaces": "VR interfaces OR immersive",
            "Mobile Interfaces": "mobile OR smartphone interfaces",
            "Web Design": "web design OR responsive design",
            "Information Architecture": "information architecture OR IA",
            "User Modeling": "user modeling OR personas",
            "Cognitive Modeling": "cognitive OR mental models",
            "Affective Computing": "affective OR emotion recognition",
            "Social Computing": "social OR collaborative systems",
            "CSCW": "CSCW OR computer-supported cooperative work",
            "Crowdsourcing": "crowdsourcing OR human computation",
            "Citizen Science": "citizen science OR participatory sensing",
            "Behavioral Design": "behavioral OR persuasive design",
            "Privacy in HCI": "privacy OR security interfaces",
            "Ethical Design": "ethical OR responsible design",
            "A/B Testing": "A/B testing OR experimentation",
            "Design Thinking": "design thinking OR creative process",
            "Prototyping": "prototyping OR rapid iteration",
            "Heuristic Evaluation": "heuristics OR expert review",
            "Task Analysis": "task analysis OR workflow",
            "Field Studies": "field studies OR ethnographic methods",

            # Robotics (30 terms)
            "Robotics": "robotics OR robotic systems",
            "Robot Control": "robot control OR motion planning",
            "SLAM": "SLAM OR simultaneous localization and mapping",
            "Path Planning": "path planning OR navigation",
            "Manipulation": "manipulation OR grasping",
            "Robot Learning": "robot learning OR RL in robotics",
            "Human-Robot": "human-robot OR HRI",
            "Swarm Robotics": "swarm OR collective robotics",
            "Autonomous Vehicles": "autonomous OR self-driving",
            "Drones": "drones OR UAVs",
            "Robot Perception": "perception OR sensor fusion",
            "Computer Vision": "computer vision OR object recognition",
            "Force Control": "force control OR impedance",
            "Legged Locomotion": "legged OR walking robots",
            "Wheeled Robots": "wheeled OR mobile robots",
            "Aerial Robots": "aerial OR flying robots",
            "Underwater Robots": "underwater OR marine robotics",
            "Medical Robotics": "medical OR surgical robots",
            "Industrial Robotics": "industrial OR factory automation",
            "Soft Robotics": "soft OR compliant robotics",
            "Modular Robots": "modular OR reconfigurable",
            "Evolutionary Robotics": "evolutionary OR genetic algorithms",
            "Neural Robotics": "neural OR brain-inspired",
            "Bio-inspired": "bio-inspired OR biomimetic",
            "Robot Safety": "safety OR collision avoidance",
            "Multi-Robot": "multi-robot OR coordination",
            "Robot Ethics": "ethics OR responsible robotics",
            "Simulation": "simulation OR digital twins",
            "Robotics Middleware": "middleware OR ROS",
            "Robot Hardware": "hardware OR actuators",

            # Visualization (30 terms)
            "Visualization": "visualization OR visual analytics",
            "InfoVis": "InfoVis OR information visualization",
            "SciVis": "SciVis OR scientific visualization",
            "Geovisualization": "geovisualization OR map-based",
            "Network Visualization": "network OR graph visualization",
            "Hierarchical Data": "hierarchical OR tree visualization",
            "Multidimensional": "multidimensional OR high-dimensional",
            "Temporal Data": "temporal OR time-series",
            "Text Visualization": "text OR document visualization",
            "Uncertainty": "uncertainty OR probabilistic visualization",
            "Volume Rendering": "volume OR 3D scalar fields",
            "Flow Visualization": "flow OR vector fields",
            "Molecular Visualization": "molecular OR biological structures",
            "Urban Visualization": "urban OR city visualization",
            "Climate Visualization": "climate OR environmental",
            "Financial Visualization": "financial OR economic",
            "Interactive": "interactive OR exploratory",
            "Perception": "perception OR visual cognition",
            "Color Theory": "color OR colormaps",
            "Visual Encoding": "visual encoding OR marks/channels",
            "Dashboard Design": "dashboards OR business intelligence",
            "Storytelling": "storytelling OR narrative visualization",
            "Visual Analytics": "visual analytics OR VA",
            "Big Data Vis": "big data OR scalable visualization",
            "Web-Based": "web-based OR D3.js",
            "Mobile Vis": "mobile OR small-screen",
            "AR/VR Vis": "AR/VR OR immersive analytics",
            "Evaluation": "evaluation OR user studies",
            "Design Patterns": "design patterns OR visualization idioms",
            "Visualization Tools": "tools OR software frameworks"
        }

    async def run(self, max_results: int = 5):
        """执行每日抓取任务"""
        collected_data = {}
        
        for topic, query in self.topics.items():
            print(f"Fetching papers for: {topic}")
            try:
                papers = await self.scraper.fetch_papers(query, max_results)
                print(topic, query)
                collected_data[topic] = papers
                print(f"Found {len(papers)} papers\n")
            except Exception as e:
                print(f"Error fetching {topic}: {str(e)}\n")

        # 更新数据并生成报告
        if collected_data:
            self.scraper.update_data(collected_data)
            self.scraper.generate_markdown()
            print("Daily update completed successfully")
        else:
            print("No new papers collected")

        return collected_data

if __name__ == "__main__":
    runner = ArxivDailyRunner()
    papers_data = asyncio.run(runner.run(max_results=100))
    with open("minisemester/arxiv/arxiv_papers.json", "w") as f:
        json.dump(papers_data, f, indent=2)